**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [19]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [7]:
v1=np.zeros(10,dtype=int)
v1[4]=1
v1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [19]:
a,b= map(int,input("Enter two numbers").split())
a1= np.random.random((a,b))
print(a1)
size = a1.size
Avg= a1.sum()/size
Avg

[[0.28636567 0.16519571]]


np.float64(0.22578068760365294)

In [20]:
Avg= a1.mean()
Avg

np.float64(0.22578068760365294)

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [12]:
def array2D(a,b):
    a1=np.ones((a,b),dtype=int)
    if a>2 and b>2:
        a1[1:a-1,1:b-1]=0
    print(a1)

array2D(4,4)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [17]:
a1= np.linspace(0,1,12)[1:-1]
a1

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [21]:
def rectangular_matrix(a,b):
    a1=np.zeros((a,b))
    for i in range(a):
        for j in range(b):
            if i==j:
                a1[i,j]=1
    return a1

a1= rectangular_matrix(3,4)
print(a1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [22]:
A= np.eye(3,4)
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
A=np.arange(0,5)
A= np.tile(A,(5,1))
print(A)
#repeat the row created 5 times

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [27]:
A= np.ones((5,5), dtype=int)*np.arange(5)
A

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [35]:
a1= np.random.randint(1,100,size=(10,2))
a1
point = np.array([2,3])

distance= np.sqrt(np.sum((a1-point)**2,axis=1))
distance_array= distance.astype(int)
distance_array

array([ 67,  80,  17,  74,  90,  26,  45,  84,  90, 111])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [6]:
# a1=np.arange(336).reshape(6,7,8)

def indexfinder(a,b,c,num):
    first=b*c
    second=c
    x=num//first
    y=(num%first)//second
    z = (num%first)%second
    return x,y,z


a1= indexfinder(6,7,8,100)
a1    


(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [12]:

a1= np.array(input().split(),dtype=float)
print(a1[::-1])



[5. 4. 3. 2. 1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [4]:
a= np.array([])
size = a.size
print("elements_count : ",size)

elements_count :  0


In [16]:
a.ndim

1

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [21]:
def softmax_function(x):
    x=np.array(x,dtype=float)
    if x.ndim !=1:
        raise Exception
    exps = np.exp(x- np.max(x))
    return exps/np.sum(exps)

In [22]:
softmax_function([2.0, 1.0, 0.1])

array([0.65900114, 0.24243297, 0.09856589])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [26]:
def create_new_array(*args):
    for i in args:
        if not isinstance(i,np.ndarray):
            raise Exception("hawa")
    new_array= np.vstack(args)
    return new_array



In [29]:
a=np.arange(12,dtype=int).reshape(3,4)
b=np.arange(12,24,dtype=int).reshape(3,4)

c='1'
new= create_new_array(a,b)
print(new)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [16]:
from datetime import datetime,timedelta
def date_array(start:datetime,end:datetime):
    l=[]
    start= datetime.strptime(start,"%Y-%m-%d")
    end= datetime.strptime(end,"%Y-%m-%d")

    while start<=end:
        new=start.strftime("%Y-%m-%d")
        l.append(new)
        start+=timedelta(days=1)
    print(l)
    

In [17]:
date_array(start = '2020-09-15', end = '2020-09-25')

['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18', '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22', '2020-09-23', '2020-09-24', '2020-09-25']


###`Q-14:` Subtract the mean of each row from a matrix.

In [23]:
def matrix(m):
    m=np.array(m)
    new_matrix= np.mean(m,axis=1,keepdims=True)
    print(m-new_matrix)

m=[[1,2,3],[4,5,6],[7,8,9]]
matrix(m)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


###`Q-15:` Swap column-1 of array with column-2 in the array.

In [24]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

m[:,[1,2]]=m[:,[2,1]]
print(m)

[[1 3 2]
 [4 6 5]
 [7 9 8]]


###`Q-16:` Replace odd elements in arrays with -1.

In [30]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# for i in range(3):
#     for j in range(3):
#         if m[i,j]%2!=0:
#             m[i,j]=-1

m[m%2!=0]=-1

print(m)

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [32]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c=[]
for i in range(len(a)):
    if a[i]>b[i]:
        c.append(a[i])
    else:
        c.append(b[i])

c=np.array(c)
print(c)


[6 3 1 7 8]


In [33]:
c=np.maximum(a,b)
print(c)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [35]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[9590, 4790, 2901, 3296, 2118],
       [ 564, 9610,  134, 3014, 3370],
       [8512, 3178, 2231, 4961, 6821],
       [ 728, 9068,  178, 2895, 8951],
       [3820, 9959,  100, 7363, 1522],
       [5673, 9617, 2522,  470, 4152],
       [1451, 3760, 1964, 5392, 3978],
       [1533, 5428, 3363, 5198, 6585]], dtype=int32)

In [36]:
max_arr1=np.max(arr1,axis=0)
min_arr1=np.min(arr1,axis=0)

Normalized_array=(arr1-max_arr1)/(max_arr1-min_arr1)
print(Normalized_array)

[[ 0.         -0.76227695 -0.1415875  -0.59001886 -0.91977386]
 [-1.         -0.05146734 -0.98958014 -0.63092993 -0.75124512]
 [-0.11943275 -1.         -0.34692001 -0.34846946 -0.28671423]
 [-0.98183027 -0.13139655 -0.97609562 -0.64819382  0.        ]
 [-0.63926435  0.         -1.          0.         -1.        ]
 [-0.43396854 -0.05043504 -0.25773828 -1.         -0.64598196]
 [-0.90172834 -0.91417195 -0.42874655 -0.28594226 -0.66940369]
 [-0.89264347 -0.66819053  0.         -0.31408675 -0.31848163]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [48]:
def  nth_largest_array(arr:np.array,n):
    if n>len(arr):
        raise Exception("value out of range")
    else:
        sorted_arr=np.sort(arr)[::-1]
        result=sorted_arr[n-1]
        return result


In [49]:
arr1=np.array([12,34,40,7,1,0])
result=nth_largest_array(arr1,1)
print(result)

40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [51]:
a=np.array([1,2,3])

output= np.concatenate((
    np.repeat(a,len(a)),np.tile(a,len(a))
))

print(output)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
