In [1]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [67]:
arr = np.random.randint(1,50,(3,4))
arr

array([[29, 14, 27, 19],
       [ 2, 39, 15, 19],
       [28, 35, 13, 34]], dtype=int32)

In [68]:
np.sort(arr)

array([[14, 19, 27, 29],
       [ 2, 15, 19, 39],
       [13, 28, 34, 35]], dtype=int32)

In [69]:
np.sort(arr,axis=1)

array([[14, 19, 27, 29],
       [ 2, 15, 19, 39],
       [13, 28, 34, 35]], dtype=int32)

In [70]:
arr[arr[:,1].argsort()]

array([[29, 14, 27, 19],
       [28, 35, 13, 34],
       [ 2, 39, 15, 19]], dtype=int32)

In [71]:
arr[np.max(arr,axis=1).argsort()]

array([[29, 14, 27, 19],
       [28, 35, 13, 34],
       [ 2, 39, 15, 19]], dtype=int32)

In [72]:
np.sort(arr.ravel()).reshape(3,4)

array([[ 2, 13, 14, 15],
       [19, 19, 27, 28],
       [29, 34, 35, 39]], dtype=int32)

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [73]:
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject =np.array ([41, 87, 72, 36, 92])

mark=np.array(marks)
mark

array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

In [74]:
np.expand_dims(extra_subject,axis=1)

array([[41],
       [87],
       [72],
       [36],
       [92]])

In [75]:
marks=np.concatenate((mark,np.expand_dims(extra_subject,axis=1)),axis=1)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [76]:
marks=np.concatenate((mark,extra_subject.reshape(-1,1)),axis=1)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [77]:
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])

In [78]:
marks=np.concatenate((marks,rec1.reshape(1,-1)),axis=0)
marks=np.concatenate((marks,rec2.reshape(1,-1)),axis=0)
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [79]:
sum_column= np.sum(marks,axis=1)
marks=np.concatenate((marks,sum_column.reshape(-1,1)),axis=1)
marks

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [80]:
marks[:,-1].argsort()[::-1]

array([5, 6, 1, 4, 3, 2, 0])

In [81]:
marks[marks[:,-1].argsort()[::-1]]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 63,  46,  90,  42,  87, 328],
       [ 67,  61,  59,  36,  92, 315],
       [ 82,   9,  29,  78,  36, 234],
       [ 39,  76,  13,  29,  72, 229],
       [ 13,  10,   9,  33,  41, 106]])

In [82]:
marks[marks[:,-1].argsort()[::-1]][0:2,:]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [91]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [92]:
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

In [93]:
np.unique(arr,axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [94]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

np.flip(arr)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [109]:
arr =np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
x=5

In [117]:
np.nonzero(np.max(arr,axis=1)>x)[0]

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [119]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [122]:
arr_merged= np.concatenate([arr1,arr2,arr3])
arr_merged


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [147]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr

array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [148]:
maximum=np.max(arr)
minimum= np.min(arr)

In [153]:
result=arr[(arr !=maximum) & (arr!=minimum)]
result

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320,
       230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587,
       227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879,
       575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395,
       525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976,
       786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621,
       453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 194, 76

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [166]:
arr = np.random.randint(10, 700, 20)
arr= np.clip(arr,min=100,max=200)
sorted_arr=np.sort(arr)
np.cumsum(sorted_arr)



array([ 100,  200,  305,  410,  572,  749,  949, 1149, 1349, 1549, 1749,
       1949, 2149, 2349, 2549, 2749, 2949, 3149, 3349, 3549])

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [11]:
arr= np.linspace(0,1,10)
arr=np.round(arr,3)
print(arr)

first= np.percentile(arr,0)
print(first)

hundred= np.percentile(arr,100)
print(hundred)

fifty=np.percentile(arr,50)
fifty_one=np.percentile(arr,51)
print(fifty)
print(fifty_one)

[0.    0.111 0.222 0.333 0.444 0.556 0.667 0.778 0.889 1.   ]
0.0
1.0
0.5
0.51008
